# -*- coding: utf-8 -*-
"""dataScienceAula02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SMIHxZbVQv17cGVnuoFuYd_pf8WOum0I
"""

import pandas as pd
import seaborn as sns

"""#Load files"""

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

movies.head()

"""#Looking movies"""

ratings.head()

"""#Analysing some notes specific by movies"""

ratings.query("movieId==1").rating

ratings.query("movieId==1").rating.mean()

ratings.query("movieId==2").rating.mean()

mean_by_movie = ratings.groupby("movieId").mean().rating
mean_by_movie.head()

mean_by_movie.plot(kind="hist")

import matplotlib.pyplot as plt
plt.figure(figsize=(5,8))
sns.boxplot(mean_by_movie)

mean_by_movie.describe()

sns.distplot(mean_by_movie)

import matplotlib.pyplot as plt

plt.hist(mean_by_movie)
plt.title("Histogram the mean to movies")